export const ADD_DAILY_UPDATE = "ADD_DAILY_UPDATE";
export const DELETE_DAILY_UPDATE = "DELETE_DAILY_UPDATE";

// COURSE MUTATIONS
export const ADD_COURSE = "ADD_COURSE";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const ALL_COURSES = "ALL_COURSES";
export const ALL_COURSES_SUCCESS = "ALL_COURSES_SUCCESS";
export const ALL_COURSES_FAILURE = "ALL_COURSES_FAILURE";

export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

export const REMOVE_COURSE = "REMOVE_COURSE";
export const REMOVE_COURSE_SUCCESS = "REMOVE_COURSE_SUCCESS";
export const REMOVE_COURSE_FAILURE = "REMOVE_COURSE_FAILURE";

export const COURSE_BY_ID = "COURSE_BY_ID";
export const COURSE_BY_ID_SUCCESS = "COURSE_BY_ID_SUCCESS";

// TEMA MUTATIONS
export const ADD_TEMA = "ADD_TEMA";
export const ADD_TEMA_SUCCESS = "ADD_TEMA_SUCCESS";
export const ADD_TEMA_FAILURE = "ADD_TEMA_FAILURE";

export const ALL_TEMAS = "ALL_TEMAS";
export const ALL_TEMAS_SUCCESS = "ALL_TEMAS_SUCCESS";
export const ALL_TEMAS_FAILURE = "ALL_TEMAS_FAILURE";

export const ALL_TEMAS_BY_COURSE_ID = "ALL_TEMAS_BY_COURSE_ID";
export const ALL_TEMAS_BY_COURSE_ID_SUCCESS = "ALL_TEMAS_BY_COURSE_SUCCESS_ID";
export const ALL_TEMAS_BY_COURSE_ID_FAILURE = "ALL_TEMAS_BY_COURSE_FAILURE";

export const TEMA_BY_ID = "TEMA_BY_ID";
export const TEMA_BY_ID_SUCCESS = "TEMA_BY_ID_SUCCESS";
export const TEMA_BY_ID_BY_COURSE = "TEMA_BY_ID_BY_COURSE";
export const TEMA_BY_ID_BY_COURSE_SUCCESS = "TEMA_BY_ID_BY_COURSE_SUCCESS";

export const UPDATE_TEMA = "UPDATE_TEMA";
export const UPDATE_TEMA_SUCCESS = "UPDATE_TEMA_SUCCESS";
export const UPDATE_TEMA_FAILURE = "UPDATE_TEMA_FAILURE";

export const REMOVE_TEMA = "DELETE_TEMA";
export const REMOVE_TEMA_SUCCESS = "DELETE_TEMA_SUCCESS";
export const REMOVE_TEMA_FAILURE = "DELETE_TEMA_FAILURE";
