export const ADD_DAILY_UPDATE = "ADD_DAILY_UPDATE";
export const DELETE_DAILY_UPDATE = "DELETE_DAILY_UPDATE";

export const ADD_COURSE = "ADD_COURSE";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const ALL_COURSES = "ALL_COURSES";
export const ALL_COURSES_SUCCESS = "ALL_COURSES_SUCCESS";
export const ALL_COURSES_FAILURE = "ALL_COURSES_FAILURE";

export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

export const REMOVE_COURSE = "REMOVE_COURSE";
export const REMOVE_COURSE_SUCCESS = "REMOVE_COURSE_SUCCESS";
export const REMOVE_COURSE_FAILURE = "REMOVE_COURSE_FAILURE";

export const COURSE_BY_ID = "COURSE_BY_ID";
export const COURSE_BY_ID_SUCCESS = "COURSE_BY_ID_SUCCESS";
